# Generated by Django 4.1 on 2023-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_auto_20230808_1831"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model1",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
